### ISSUE TITLE
Add Quotes in error message, to make it parseable as a hash

### ISSUE THREAD

**Issue by mweaverh** [cloudfoundry/membrane#3]
Feature request (will send PR):

Instead of errors like:
`e=#<Membrane::SchemaValidationError: { sleep => Expected instance of Time, given an instance of String }`
do this:
`e=#<Membrane::SchemaValidationError: { 'sleep' => 'Expected instance of Time, given an instance of String'}`

So that 

```
eval(e.to_s)
```

returns a hash.

Probably need to make this configurable. Which will require adding a little config mechanism.

**Comment by karlkfi** [comment]
Moving discussion to the PR: #4 

CF Community Pair (@karlkfi & @jfmyers9)
